{ config, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix # Generated by nixos-generate-config
  ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = "nixos";
  networking.networkmanager.enable = true;

  time.timeZone = "UTC";
  i18n.defaultLocale = "en_US.UTF-8";

  # Strictly Baseline p y t h o n 3 and UV. Zero global packages.
  environment.systemPackages = with pkgs; [
    git
    wget
    curl
    python3
    uv
    vmware-workstation
    vulkan-tools
    clinfo
    radeontop
    llama-cpp
    ollama
    # Terminals & Shells
    kitty
    alacritty
    nushell
    starship
    zoxide
    fzf
    ripgrep
    fd
    bat
    eza
    # Desktop environment base
    picom
    rofi
    dunst
    feh
    flameshot
    xclip
    qutebrowser
    mpv
  ];

  # Enforce AMDGPU kernel module loading for RX 480
  boot.initrd.kernelModules = [ "amdgpu" ];
  services.xserver.videoDrivers = [ "amdgpu" ];

  # Graphics / Vulkan configuration tailored for the RX 480
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      vulkan-loader
      vulkan-validation-layers
      vulkan-extension-layer
      vulkan-tools
      amdvlk
    ];
    extraPackages32 = with pkgs.pkgsi686Linux; [
      amdvlk
    ];
  };

  # Explicitly force AMDVLK/Vulkan backend environments
  environment.variables = {
    VK_ICD_FILENAMES = "/run/opengl-driver/share/vulkan/icd.d/amd_icd64.json";
    GGML_VULKAN = "1";
    HSA_OVERRIDE_GFX_VERSION = "8.0.3"; # Polaris fallback
  };

  # Extreme optimization for 138GB RAM and LLM context caching
  boot.kernel.sysctl = {
    # Drop swappiness to near zero to prioritize RAM usage over disk
    "vm.swappiness" = 1;
    "vm.vfs_cache_pressure" = 50;

    # Enable aggressive HugePages mapping (16GB allocated for 2MB pages)
    # 8192 pages * 2MB = 16384 MB dedicated to hugepages for LLM memory pinning
    "vm.nr_hugepages" = 8192;
    "vm.hugetlb_shm_group" = 0;
  };

  # Keep heavy I/O ops entirely in RAM
  fileSystems."/tmp" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = [ "nosuid" "nodev" "size=64G" ];
  };

  fileSystems."/var/tmp" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = [ "nosuid" "nodev" "size=32G" ];
  };

  # Bare-metal VMware Workstation Pro Host Configuration
  virtualisation.vmware.host.enable = true;
  networking.firewall.trustedInterfaces = [ "vmnet1" "vmnet8" ];

  # Desktop Environment: Qtile
  services.xserver = {
    enable = true;
    windowManager.qtile.enable = true;
    displayManager.startx.enable = true;
  };

  users.users.architect = {
    isNormalUser = true;
    description = "System Architect";
    extraGroups = [ "networkmanager" "wheel" "video" "render" "vmware" ];
    shell = pkgs.nushell;
  };

  system.stateVersion = "24.05";
}
